[package]
name = "moxie-interp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
moxie-types.workspace = true
moxie-graph.workspace = true
moxie-format.workspace = true
moxie-oracles.workspace = true
moxie-state.workspace = true

[lints]
workspace = true
