//! Bounded reader acceptance: round trip, budget, checksum, refusals, paths.
//!
//! Payload artifacts are generated by the helpers below into a temporary
//! directory, deterministically from a seed. No binary blob enters git, and
//! the generator is itself the demonstration that the format can be written
//! as well as read.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use moxie_format::sha256_hex;
use moxie_storage::{Artifact, ByteBudget, HeaderBudget, Shard};

/// Thread-local live-allocation accounting for the memory gate below.
///
/// Global, so it observes the real `Artifact::read_tensor` path including
/// file open, hashing and validation -- not a model of it. Thread-local, so
/// concurrently running tests on other threads cannot pollute the measured
/// thread's peak. Only heap `alloc`/`dealloc` pairs are counted; the
/// caller's destination buffer is allocated before the measurement starts,
/// because it is caller-owned, not reader-owned.
mod alloc_measure {
    use std::alloc::{GlobalAlloc, Layout, System};
    use std::cell::Cell;

    thread_local! {
        static LIVE: Cell<usize> = const { Cell::new(0) };
        static PEAK: Cell<usize> = const { Cell::new(0) };
        static BASE: Cell<usize> = const { Cell::new(0) };
    }

    pub struct Counting;

    // SAFETY: every call forwards to the system allocator with the same
    // layout, and the counters only observe sizes; no allocation contract
    // is altered.
    unsafe impl GlobalAlloc for Counting {
        unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
            // SAFETY: same layout forwarded to the system allocator.
            let p = unsafe { System.alloc(layout) };
            if !p.is_null() && layout.size() > 0 {
                LIVE.with(|live| {
                    let n = live.get().saturating_add(layout.size());
                    live.set(n);
                    PEAK.with(|peak| {
                        if n > peak.get() {
                            peak.set(n);
                        }
                    });
                });
            }
            p
        }

        unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
            // SAFETY: `ptr`/`layout` are the pair a matching `alloc` handed
            // out, forwarded unchanged.
            unsafe { System.dealloc(ptr, layout) };
            if layout.size() > 0 {
                LIVE.with(|live| live.set(live.get().saturating_sub(layout.size())));
            }
        }
    }

    pub fn reset_peak() {
        let live = LIVE.with(|l| l.get());
        BASE.with(|b| b.set(live));
        PEAK.with(|p| p.set(live));
    }

    /// Peak live heap bytes on this thread above the reset baseline.
    pub fn peak_additional() -> usize {
        PEAK.with(|p| p.get())
            .saturating_sub(BASE.with(|b| b.get()))
    }
}

#[global_allocator]
static GLOBAL: alloc_measure::Counting = alloc_measure::Counting;

const HEX_EMPTY: &str = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

/// Deterministic bytes from a seed. An LCG, not a quality RNG: the only
/// property needed is same-seed/same-bytes, asserted below.
fn prng_bytes(seed: u64, n: usize) -> Vec<u8> {
    let mut state = seed | 1;
    let mut out = Vec::with_capacity(n);
    while out.len() < n {
        state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        out.extend_from_slice(&(state >> 33).to_le_bytes());
    }
    out.truncate(n);
    out
}

/// Finite BF16 payload bytes: same PRNG, with any all-ones exponent cleared so
/// every element is a finite weight the reader must accept.
fn finite_bf16_bytes(seed: u64, nbytes: usize) -> Vec<u8> {
    assert_eq!(nbytes % 2, 0);
    let mut b = prng_bytes(seed, nbytes);
    for pair in b.chunks_exact_mut(2) {
        let mut bits = u16::from_le_bytes([pair[0], pair[1]]);
        if (bits & 0x7F80) == 0x7F80 {
            bits &= 0x7F7F;
            pair.copy_from_slice(&bits.to_le_bytes());
        }
    }
    b
}

struct TensorSpec {
    role: &'static str,
    shape: &'static str,
    precision: &'static str,
    chunk: &'static str,
    offset: u64,
    payload: Vec<u8>,
    extra: &'static str,
}

fn tensor_block(t: &TensorSpec, order: usize) -> String {
    format!(
        r#"[[tensors]]
role = "{role}"
shape = [{shape}]
precision = "{precision}"
chunk = "{chunk}"
offset = {offset}
length = {length}
sha256 = "{sha}"
alignment = 2
logical_order = {order}
{extra}
"#,
        role = t.role,
        shape = t.shape,
        precision = t.precision,
        chunk = t.chunk,
        offset = t.offset,
        length = t.payload.len(),
        sha = sha256_hex(&t.payload),
        order = order,
        extra = t.extra,
    )
}

fn manifest_for(tensors: &[TensorSpec], completeness: &str) -> String {
    let mut blocks = String::new();
    for (i, t) in tensors.iter().enumerate() {
        blocks.push_str(&tensor_block(t, i));
    }
    format!(
        r#"schema_version = 1
required_features = []
endianness = "little"

[source]
model = "test-artifact"
revision = "t1"
license = "apache-2.0"
[[source.files]]
path = "orig.bin"
sha256 = "{HEX_EMPTY}"

[tokenizer]
name = "tok"
version = "1"
digest = "{HEX_EMPTY}"

[template]
name = "tpl"
version = "1"
digest = "{HEX_EMPTY}"

[architecture]
name = "arch"
version = "1"
[architecture.metadata]
hidden = 8

[provenance]
scale_convention = "affine-v1"
quantizer = "none"
calibration = "none"

{blocks}
[[excluded]]
role = "old"
reason = "removed upstream"

[completeness]
{completeness}
"#
    )
}

/// Write chunks (concatenating payloads per chunk file at their offsets) and
/// the manifest. Returns the artifact directory.
fn write_artifact(dir: &Path, tensors: &[TensorSpec], completeness: &str) -> PathBuf {
    std::fs::create_dir_all(dir).unwrap();
    // Group payloads by chunk, sorted by offset.
    let mut by_chunk: BTreeMap<&str, Vec<&TensorSpec>> = BTreeMap::new();
    for t in tensors {
        by_chunk.entry(t.chunk).or_default().push(t);
    }
    for (chunk, mut list) in by_chunk {
        list.sort_by_key(|t| t.offset);
        let end: usize = list
            .iter()
            .map(|t| t.offset as usize + t.payload.len())
            .max()
            .unwrap_or(0);
        let mut bytes = vec![0u8; end];
        for t in list {
            bytes[t.offset as usize..t.offset as usize + t.payload.len()]
                .copy_from_slice(&t.payload);
        }
        std::fs::write(dir.join(chunk), &bytes).unwrap();
    }
    std::fs::write(
        dir.join("manifest.toml"),
        manifest_for(tensors, completeness),
    )
    .unwrap();
    dir.to_path_buf()
}

fn test_dir(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "moxie-storage-{name}-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

fn complete() -> &'static str {
    "status = \"complete\"\nmissing = []"
}

#[test]
fn the_generator_is_deterministic() {
    assert_eq!(prng_bytes(7, 64), prng_bytes(7, 64));
    assert_ne!(prng_bytes(7, 64), prng_bytes(8, 64));
}

#[test]
fn round_trip_two_tensors_in_two_chunks_is_byte_for_byte() {
    let dir = test_dir("roundtrip");
    let a = finite_bf16_bytes(1, 32); // 4x4 BF16
    let b = finite_bf16_bytes(2, 64); // 4x8 BF16
    let tensors = vec![
        TensorSpec {
            role: "block0.q",
            shape: "4, 4",
            precision: "bf16-v1",
            chunk: "chunk0.bin",
            offset: 0,
            payload: a.clone(),
            extra: "",
        },
        TensorSpec {
            role: "block0.k",
            shape: "4, 8",
            precision: "bf16-v1",
            chunk: "chunk1.bin",
            offset: 0,
            payload: b.clone(),
            extra: "",
        },
    ];
    write_artifact(&dir, &tensors, complete());
    let art = Artifact::open(&dir).expect("valid artifact opens");
    assert_eq!(art.read_budget(), ByteBudget::DEFAULT);
    let mut out_a = vec![0u8; 32];
    let mut out_b = vec![0u8; 64];
    assert_eq!(art.read_tensor("block0.q", &mut out_a).unwrap(), 32);
    assert_eq!(art.read_tensor("block0.k", &mut out_b).unwrap(), 64);
    assert_eq!(out_a, a);
    assert_eq!(out_b, b);
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn opening_reads_no_payload_byte() {
    // The manifest's checksum is deliberately wrong: open must still succeed
    // (it stats, never hashes), and only the read fails.
    let dir = test_dir("no-payload-at-open");
    let payload = finite_bf16_bytes(3, 8);
    let tensors = vec![TensorSpec {
        role: "w",
        shape: "2, 2",
        precision: "bf16-v1",
        chunk: "c.bin",
        offset: 0,
        payload: payload.clone(),
        extra: "",
    }];
    write_artifact(&dir, &tensors, complete());
    // Rewrite the manifest with a wrong checksum for the same layout.
    let evil = manifest_for(&tensors, complete()).replacen(&sha256_hex(&payload), HEX_EMPTY, 1);
    std::fs::write(dir.join("manifest.toml"), evil).unwrap();
    let art = Artifact::open(&dir).expect("open hashes no payload");
    let mut out = vec![0u8; 8];
    let e = art.read_tensor("w", &mut out).unwrap_err();
    assert!(e.to_string().contains("checksum mismatch"), "{e}");
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn a_short_buffer_is_an_error_naming_both_sizes_never_a_partial_read() {
    let dir = test_dir("short-buffer");
    let payload = finite_bf16_bytes(4, 32);
    write_artifact(
        &dir,
        &[TensorSpec {
            role: "w",
            shape: "4, 4",
            precision: "bf16-v1",
            chunk: "c.bin",
            offset: 0,
            payload,
            extra: "",
        }],
        complete(),
    );
    let art = Artifact::open(&dir).unwrap();
    let mut short = vec![0u8; 31];
    let e = art.read_tensor("w", &mut short).unwrap_err();
    let msg = e.to_string();
    assert!(msg.contains("32") && msg.contains("31"), "{msg}");
    assert!(msg.contains("never a partial"), "{msg}");
    // An unknown role is a typed error, not a panic.
    let mut buf = vec![0u8; 32];
    assert!(art.read_tensor("nope", &mut buf).is_err());
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn a_corrupted_payload_byte_is_caught_by_the_checksum_naming_the_tensor() {
    let dir = test_dir("corrupt");
    let payload = finite_bf16_bytes(5, 32);
    write_artifact(
        &dir,
        &[TensorSpec {
            role: "victim",
            shape: "4, 4",
            precision: "bf16-v1",
            chunk: "c.bin",
            offset: 0,
            payload: payload.clone(),
            extra: "",
        }],
        complete(),
    );
    // Flip one byte in the chunk after the manifest was written.
    let mut raw = std::fs::read(dir.join("c.bin")).unwrap();
    raw[10] ^= 0xFF;
    // Keep it finite so the failure is the checksum, not the BF16 rule: if the
    // flip made it non-finite the test would prove the wrong rule.
    let bits = u16::from_le_bytes([raw[10] & !1, raw[11]]);
    if (bits & 0x7F80) == 0x7F80 {
        raw[11] &= 0x7E;
    }
    std::fs::write(dir.join("c.bin"), &raw).unwrap();
    let art = Artifact::open(&dir).unwrap();
    let mut out = vec![0u8; 32];
    let e = art.read_tensor("victim", &mut out).unwrap_err();
    let msg = e.to_string();
    assert!(msg.contains("victim"), "{msg}");
    assert!(msg.contains("checksum mismatch"), "{msg}");
    assert!(msg.contains("not to be trusted"), "{msg}");
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn a_nonfinite_bf16_weight_is_caught_at_load() {
    let dir = test_dir("nonfinite");
    // Payload whose first element is a quiet NaN, with a matching checksum so
    // the failure is the finiteness rule rather than the hash.
    let mut payload = finite_bf16_bytes(6, 8);
    payload[0..2].copy_from_slice(&0x7FC0u16.to_le_bytes());
    write_artifact(
        &dir,
        &[TensorSpec {
            role: "w",
            shape: "2, 2",
            precision: "bf16-v1",
            chunk: "c.bin",
            offset: 0,
            payload,
            extra: "",
        }],
        complete(),
    );
    let art = Artifact::open(&dir).unwrap();
    let mut out = vec![0u8; 8];
    let e = art.read_tensor("w", &mut out).unwrap_err();
    assert!(e.to_string().contains("non-finite"), "{e}");
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn an_affine_tensor_validates_then_refuses_to_read_naming_m3() {
    let dir = test_dir("affine");
    // 8x32 INT4: packed codes would be 128 bytes; the payload is reserved but
    // never decoded by v1.
    let payload = prng_bytes(7, 128);
    write_artifact(
        &dir,
        &[TensorSpec {
            role: "q",
            shape: "8, 32",
            precision: "affine-int4-v1",
            chunk: "c.bin",
            offset: 0,
            payload,
            extra: "group_rule = \"contiguous-32\"\nscale_dtype = \"f16\"\nzero_point = \"symmetric\"",
        }],
        complete(),
    );
    let art = Artifact::open(&dir).expect("affine descriptors validate in v1");
    let mut out = vec![0u8; 128];
    let e = art.read_tensor("q", &mut out).unwrap_err();
    assert!(e.to_string().contains("M3"), "{e}");
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn a_partial_artifact_opens_for_inspection_and_refuses_every_read() {
    let dir = test_dir("partial");
    let payload = finite_bf16_bytes(8, 8);
    write_artifact(
        &dir,
        &[TensorSpec {
            role: "w",
            shape: "2, 2",
            precision: "bf16-v1",
            chunk: "c.bin",
            offset: 0,
            payload,
            extra: "",
        }],
        "status = \"partial\"\nmissing = [\"gone\"]",
    );
    let art = Artifact::open(&dir).expect("partial opens for inspection");
    let mut out = vec![0u8; 8];
    let e = art.read_tensor("w", &mut out).unwrap_err();
    assert!(e.to_string().contains("partial"), "{e}");
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn a_tensor_eight_times_the_budget_reads_correctly() {
    // 8 KiB tensor under a 1 KiB budget: the reader holds slices, never the
    // tensor. Slice-size counting lives in the unit test over the same pump;
    // this is the end-to-end half, proving a tiny budget still reads exactly.
    let dir = test_dir("budget");
    let budget = ByteBudget::new(1024).unwrap();
    let payload = finite_bf16_bytes(9, 8192);
    write_artifact(
        &dir,
        &[TensorSpec {
            role: "big",
            shape: "64, 64",
            precision: "bf16-v1",
            chunk: "c.bin",
            offset: 0,
            payload: payload.clone(),
            extra: "",
        }],
        complete(),
    );
    let art = Artifact::open_with_budget(&dir, budget).expect("open with small budget");
    assert_eq!(art.read_budget().bytes(), 1024);
    let mut out = vec![0u8; 8192];
    assert_eq!(art.read_tensor("big", &mut out).unwrap(), 8192);
    assert_eq!(out, payload);
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn peak_live_allocation_stays_within_budget_and_constant_in_tensor_size() {
    // The declared memory gate, measured with a counting allocator around
    // the real `Artifact::read_tensor` -- file open, slice reads, streaming
    // hash, BF16 validation and checksum verification included. Three
    // properties: the peak fits the budget; it does not move when the tensor
    // grows 8x (reader-owned allocation is O(1)); and the success path holds
    // zero live heap -- hashing and hex run on stack arrays, so any heap
    // byte at all is a regression (the old finalizer peaked at 128 B here).
    // File-open costs are inside the measurement, not excluded from it.
    //
    // Equal-length directory names keep paths identical in length, so any
    // size-dependent allocation would show as a peak difference.
    let budget = ByteBudget::new(1024).unwrap();
    let mut peaks = Vec::new();
    for (name, seed, shape, nbytes) in [
        ("gate-small", 21u64, "64, 64", 8192usize),
        ("gate-large", 22u64, "128, 256", 65536usize),
    ] {
        assert_eq!(name.len(), 10);
        let dir = test_dir(name);
        let payload = finite_bf16_bytes(seed, nbytes);
        write_artifact(
            &dir,
            &[TensorSpec {
                role: "t",
                shape,
                precision: "bf16-v1",
                chunk: "c.bin",
                offset: 0,
                payload: payload.clone(),
                extra: "",
            }],
            complete(),
        );
        let art = Artifact::open_with_budget(&dir, budget).expect("open");
        // Warmup outside the measurement: page cache, lazy std state.
        let mut warm = vec![0u8; nbytes];
        assert_eq!(art.read_tensor("t", &mut warm).unwrap(), nbytes);
        assert_eq!(warm, payload);
        // The destination is caller-owned: allocate it before measuring.
        let mut out = vec![0u8; nbytes];
        alloc_measure::reset_peak();
        assert_eq!(art.read_tensor("t", &mut out).unwrap(), nbytes);
        let peak = alloc_measure::peak_additional();
        assert_eq!(out, payload);
        assert!(
            peak <= budget.bytes(),
            "tensor {nbytes} B under budget {}: peak live allocation was {peak} B",
            budget.bytes()
        );
        assert_eq!(
            peak, 0,
            "success-path heap must be zero (stack-only hashing): peak was {peak} B for a {nbytes} B tensor"
        );
        peaks.push(peak);
        std::fs::remove_dir_all(&dir).ok();
    }
    assert_eq!(
        peaks[0], peaks[1],
        "peak live allocation must not move with tensor size: {peaks:?}"
    );
}

#[test]
fn long_pathnames_do_not_enter_the_read_budget() {
    // Review round 2, reproduced: `read_tensor` reopened the chunk by
    // pathname, and `File::open` allocates ~path length -- 2,054 B under ten
    // nested 200-character directories for an 8,192 B tensor under a 1,024 B
    // budget. Chunk files are now opened once at `Artifact::open` and read
    // position-independently, so pathname length cannot allocate during a
    // read. Same gate as the short-path test: fits the budget, zero heap.
    let mut deep = test_dir("gate-longpath");
    for _ in 0..10 {
        deep = deep.join("d".repeat(200));
    }
    std::fs::create_dir_all(&deep).unwrap();
    assert!(deep.as_os_str().len() > 2000);
    let nbytes = 8192usize;
    let budget = ByteBudget::new(1024).unwrap();
    let payload = finite_bf16_bytes(23, nbytes);
    write_artifact(
        &deep,
        &[TensorSpec {
            role: "t",
            shape: "64, 64",
            precision: "bf16-v1",
            chunk: "c.bin",
            offset: 0,
            payload: payload.clone(),
            extra: "",
        }],
        complete(),
    );
    let art = Artifact::open_with_budget(&deep, budget).expect("open");
    let mut warm = vec![0u8; nbytes];
    assert_eq!(art.read_tensor("t", &mut warm).unwrap(), nbytes);
    let mut out = vec![0u8; nbytes];
    alloc_measure::reset_peak();
    assert_eq!(art.read_tensor("t", &mut out).unwrap(), nbytes);
    let peak = alloc_measure::peak_additional();
    assert_eq!(out, payload);
    assert!(
        peak <= budget.bytes(),
        "long-path read: peak live allocation was {peak} B over budget {}",
        budget.bytes()
    );
    assert_eq!(
        peak, 0,
        "long-path read must hold zero live heap, as the short-path one does: peak was {peak} B"
    );
    std::fs::remove_dir_all(test_dir_parent(&deep)).ok();
}

/// The `test_dir` root a deep tree was built under, for cleanup.
fn test_dir_parent(deep: &Path) -> PathBuf {
    let mut p = deep;
    for _ in 0..10 {
        p = p.parent().unwrap();
    }
    p.to_path_buf()
}

#[test]
fn chunk_references_cannot_escape_the_artifact_directory() {
    // Separator, parent traversal and absolute path: refused on the string,
    // before any path is joined.
    for chunk in ["sub/c.bin", "../c.bin", "/tmp/c.bin"] {
        let dir = test_dir("escape");
        let payload = finite_bf16_bytes(10, 8);
        // Write a valid chunk file, but name a different chunk in the manifest.
        std::fs::write(dir.join("c.bin"), &payload).unwrap();
        let tensors = vec![TensorSpec {
            role: "w",
            shape: "2, 2",
            precision: "bf16-v1",
            chunk,
            offset: 0,
            payload: payload.clone(),
            extra: "",
        }];
        std::fs::write(
            dir.join("manifest.toml"),
            manifest_for(&tensors, complete()),
        )
        .unwrap();
        match Artifact::open(&dir) {
            Ok(_) => panic!("chunk {chunk:?} must not open"),
            Err(e) => assert_eq!(e.kind(), "invalid_artifact"),
        }
        std::fs::remove_dir_all(&dir).ok();
    }
}

#[test]
fn a_symlink_pointing_outside_is_rejected_after_opening() {
    let dir = test_dir("symlink");
    let outside = test_dir("symlink-outside");
    let payload = finite_bf16_bytes(11, 8);
    std::fs::write(outside.join("real.bin"), &payload).unwrap();
    let tensors = vec![TensorSpec {
        role: "w",
        shape: "2, 2",
        precision: "bf16-v1",
        chunk: "link.bin",
        offset: 0,
        payload,
        extra: "",
    }];
    std::fs::write(
        dir.join("manifest.toml"),
        manifest_for(&tensors, complete()),
    )
    .unwrap();
    if std::os::unix::fs::symlink(outside.join("real.bin"), dir.join("link.bin")).is_err() {
        println!("SKIP symlink test: symlinks cannot be created here");
        std::fs::remove_dir_all(&dir).ok();
        std::fs::remove_dir_all(&outside).ok();
        return;
    }
    match Artifact::open(&dir) {
        Ok(_) => panic!("a symlink pointing outside must be rejected"),
        Err(e) => assert_eq!(e.kind(), "invalid_artifact"),
    }
    std::fs::remove_dir_all(&dir).ok();
    std::fs::remove_dir_all(&outside).ok();
}

#[test]
fn the_manifest_size_cap_errors_before_parsing() {
    // Pad with comments past 4 MiB + 1. Comments keep it valid TOML, so the
    // failure is the cap rather than the parser.
    let dir = test_dir("bigmanifest");
    let payload = finite_bf16_bytes(12, 8);
    write_artifact(
        &dir,
        &[TensorSpec {
            role: "w",
            shape: "2, 2",
            precision: "bf16-v1",
            chunk: "c.bin",
            offset: 0,
            payload,
            extra: "",
        }],
        complete(),
    );
    let mut text = std::fs::read_to_string(dir.join("manifest.toml")).unwrap();
    while text.len() <= moxie_format::manifest::MAX_MANIFEST_BYTES {
        text.push_str("# padding to bound the parse itself ....................\n");
    }
    std::fs::write(dir.join("manifest.toml"), &text).unwrap();
    match Artifact::open(&dir) {
        Ok(_) => panic!("an over-cap manifest must error at the limit"),
        Err(e) => assert!(e.to_string().contains("cap"), "{e}"),
    }
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn truncation_at_open_names_the_short_chunk() {
    let dir = test_dir("truncate");
    let payload = finite_bf16_bytes(13, 8);
    write_artifact(
        &dir,
        &[TensorSpec {
            role: "w",
            shape: "2, 2",
            precision: "bf16-v1",
            chunk: "c.bin",
            offset: 0,
            payload,
            extra: "",
        }],
        complete(),
    );
    // Truncate the chunk after the manifest was written.
    std::fs::write(dir.join("c.bin"), [0u8; 4]).unwrap();
    match Artifact::open(&dir) {
        Ok(_) => panic!("a truncated chunk must fail at open"),
        Err(e) => assert!(e.to_string().contains("truncation"), "{e}"),
    }
    std::fs::remove_dir_all(&dir).ok();
}

/// Task 0018: a header longer than the file it claims to describe is refused
/// before the allocation, not after a short read.
///
/// The budget cases live in `tests/header_budget.rs`, which needs a global
/// counting allocator and therefore its own executable.
#[test]
fn a_shard_header_longer_than_its_file_is_refused_before_it_is_allocated() {
    use std::io::Write;
    let dir = std::env::temp_dir().join(format!(
        "moxie-shard-truncated-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("short.safetensors");
    let mut f = std::fs::File::create(&path).unwrap();
    // Declares a 1 MiB header in a 16-byte file.
    f.write_all(&(1u64 << 20).to_le_bytes()).unwrap();
    f.write_all(&[0u8; 8]).unwrap();
    drop(f);
    let e = moxie_storage::Shard::open(&path).unwrap_err();
    assert!(
        matches!(e, moxie_types::Error::InvalidArtifact { .. }),
        "expected a typed artifact error, got {e}"
    );
    std::fs::remove_dir_all(&dir).ok();
}

use std::io::Write as _;

fn budget_tempdir() -> std::path::PathBuf {
    let p = std::env::temp_dir().join(format!(
        "moxie-header-admission-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    std::fs::create_dir_all(&p).unwrap();
    p
}

fn budget_shard(dir: &std::path::Path, tensors: usize) -> (std::path::PathBuf, u64) {
    let mut json = String::from("{");
    for i in 0..tensors {
        if i > 0 {
            json.push(',');
        }
        json.push_str(&format!(
            "\"{i}\":{{\"dtype\":\"U8\",\"shape\":[1],\"data_offsets\":[{i},{}]}}",
            i + 1
        ));
    }
    json.push('}');
    let path = dir.join("admission.safetensors");
    let mut f = std::fs::File::create(&path).unwrap();
    f.write_all(&(json.len() as u64).to_le_bytes()).unwrap();
    f.write_all(json.as_bytes()).unwrap();
    f.write_all(&vec![0u8; tensors]).unwrap();
    (path, json.len() as u64 + 8)
}

/// Admission is against the estimated peak, and refuses with the estimate
/// rather than with the serialized length a caller cannot act on.
///
/// No counting allocator here: this is about the rule, not the measurement.
/// The measurement is `tests/header_budget.rs`, which needs its own executable.
#[test]
fn admission_refuses_against_the_estimated_peak_not_the_serialized_length() {
    let dir = budget_tempdir();
    let (path, serialized) = budget_shard(&dir, 1000);
    let estimate = HeaderBudget::estimated_peak(serialized).unwrap();
    assert!(
        estimate > serialized * 4,
        "the estimate must exceed the serialized length substantially, or this \
         test is not checking anything"
    );

    let tiny_payload = ByteBudget::new(16).unwrap();

    // A budget that covers the serialized bytes but not the parse is refused,
    // which is exactly the case the second review reproduced.
    let serialized_only = HeaderBudget::new(serialized).unwrap();
    assert!(matches!(
        Shard::open_with_limits(&path, tiny_payload, serialized_only),
        Err(moxie_types::Error::CapacityExceeded { requested_bytes, available_bytes, .. })
            if requested_bytes == estimate && available_bytes == serialized
    ));

    // One byte below the estimate is refused; the estimate itself is enough.
    let short = HeaderBudget::new(estimate - 1).unwrap();
    assert!(matches!(
        Shard::open_with_limits(&path, tiny_payload, short),
        Err(moxie_types::Error::CapacityExceeded { .. })
    ));
    let exact = HeaderBudget::new(estimate).unwrap();
    assert!(Shard::open_with_limits(&path, tiny_payload, exact).is_ok());

    // And the payload budget still does not govern the header.
    assert!(Shard::open_with_budget(&path, tiny_payload).is_ok());
    // The budget reports the largest serialized header it admits, and this one
    // is at that edge.
    assert!(exact.max_serialized() + 1 > serialized);

    assert!(HeaderBudget::new(0).is_none());
    assert!(
        HeaderBudget::new(
            HeaderBudget::estimated_peak(moxie_format::safetensors::MAX_HEADER_BYTES).unwrap() + 1
        )
        .is_none()
    );
    std::fs::remove_dir_all(&dir).ok();
}
