//! M2's exit clause: a whole working set, out of device memory, with its byte
//! and cost trace reconciled against the resource ledger.
//!
//! Two cases, and the pair is the deliverable rather than either one alone.
//!
//! * **`whole-set-decode`** runs a decode-shaped row batch through **every one
//!   of the designated artifact's 30 routed layers**, in two cache
//!   configurations, and requires every layer's device answer to equal the CPU
//!   candidate's over the same bytes. The roomy configuration is where the
//!   planner's prediction is an equality; the tight one is where it is a
//!   declared lower bound. Both reconcile exactly.
//! * **`whole-set-full`** demands **every expert of every routed layer** --
//!   45,675,970,560 B, 88.5% of the artifact and 1.77 times the largest card on
//!   this machine -- through a device cache holding sixteen of one layer's 128
//!   experts. It is the out-of-device-memory clause, and it needs no restricted
//!   budget argument to be one.
//!
//! **What is synthetic is said here, before any result.** The activations are
//! generated by this test and **the routes are written by this test**;
//! `whole-set-full`'s route is constructed so that its union is the whole expert
//! set. The **bytes are the artifact's own**, read from its shards at their real
//! offsets. This is not model support, no quality claim follows (O2), and no
//! route-distribution claim follows either.
//!
//! **`whole-set-full` is deliberately not compared against the CPU candidate**,
//! and the arithmetic rather than an adjective: its 3,840 row-expert products
//! are 2.28e10 multiply-adds, which at the rate this lane's debug host candidate
//! measures is about nine minutes per pass, and what it would buy is a repeat of
//! a comparison `whole-set-decode` already makes on every one of the 30 layers.
//! What it adds instead is bitwise equality of all three cards' answers to each
//! other, which also checks sm_86 against sm_120 and costs nothing.
//!
//! Skipped, loudly, when the artifact is not on this machine.
#![cfg(feature = "driver")]

use std::path::{Path, PathBuf};
use std::sync::{Mutex, MutexGuard};
use std::time::Instant;

use moxie_cuda::RankContext;
use moxie_executor::grouped::{ExpertRoles, GroupedRun};
use moxie_executor::residency::{DeviceResidency, ShardSource};
use moxie_executor::trace::{LayerSnapshot, LayerTrace, StepTrace};
use moxie_graph::{CombineOrder, ExpertActivation, OpParams};
use moxie_memory::{
    ArtifactId, CapacitySnapshot, Ledger, ResidencyAuthority, ResidencyRequest, TurnId,
};
use moxie_plan::expert::{
    ChunkResidency, Exactness, ExpertBudget, ExpertKernels, ExpertPolicy, ResidentChunks,
    compile_experts,
};
use moxie_storage::Shard;
use moxie_types::{RankId, Scope, StrategyControl};

/// The designated BF16 MoE. A read-only input: nothing here writes, copies,
/// converts or downloads anything.
const ARTIFACT: &str = "/fast/models/google/gemma-4-26B-A4B-it";
const SHARDS: [&str; 2] = [
    "model-00001-of-00002.safetensors",
    "model-00002-of-00002.safetensors",
];

const LAYERS: u32 = 30;
const HIDDEN: u64 = 2816;
const INTERMEDIATE: u64 = 704;
const EXPERTS: u64 = 128;
const TOP_K: u64 = 8;
const GATE_UP_PER_EXPERT: u64 = 2 * INTERMEDIATE * HIDDEN * 2;
const DOWN_PER_EXPERT: u64 = HIDDEN * INTERMEDIATE * 2;
const EXPERT_TOTAL: u64 = GATE_UP_PER_EXPERT + DOWN_PER_EXPERT;
/// One layer's 128 experts.
const LAYER_EXPERTS: u64 = EXPERTS * EXPERT_TOTAL;
/// Every routed layer's experts: the number M2's exit is about.
const WHOLE_SET: u64 = LAYERS as u64 * LAYER_EXPERTS;
const MIB: u64 = 1024 * 1024;

/// A `RankContext` is exclusive per device and `cargo test` runs a binary's
/// tests in parallel threads. Serialising them is not a workaround: the
/// exclusivity is the property task 0007 established deliberately.
static DEVICE: Mutex<()> = Mutex::new(());

fn one_at_a_time() -> MutexGuard<'static, ()> {
    DEVICE.lock().unwrap_or_else(|e| e.into_inner())
}

fn artifact_id() -> ArtifactId {
    // The artifact's own index digest, recorded in the bring-up record. Not a
    // path: the authority may not learn what one is.
    ArtifactId::new("sha256:907826a6e46ff454272bd6db1fee629d5531a2303be22986d825a0871d7dc7a7")
        .unwrap()
}

fn tensor_names(layer: u32) -> (String, String) {
    (
        format!("model.language_model.layers.{layer}.experts.gate_up_proj"),
        format!("model.language_model.layers.{layer}.experts.down_proj"),
    )
}

fn roles(layer: u32) -> ExpertRoles {
    ExpertRoles {
        artifact: artifact_id(),
        gate_up_role: format!("experts_gate_up.{layer}"),
        down_role: format!("experts_down.{layer}"),
        format_version: 1,
    }
}

/// Which shard holds each tensor, read from the shards' own headers.
///
/// Not assumed from the layer index: a two-shard split is a property of the
/// artifact, and guessing where the boundary falls is how a test comes to read
/// the wrong bytes confidently.
fn shard_of(shards: &[Shard], tensor: &str) -> usize {
    shards
        .iter()
        .position(|s| s.header().get(tensor).is_ok())
        .unwrap_or_else(|| panic!("no shard holds {tensor}"))
}

/// Every layer's two expert tensors, bound to the shard that holds them.
fn source(dir: &Path) -> ShardSource {
    let open = || -> Vec<Shard> {
        SHARDS
            .iter()
            .map(|name| Shard::open(&dir.join(name)).unwrap())
            .collect()
    };
    let probe = open();
    let mut src = ShardSource::new(artifact_id(), open());
    for layer in 0..LAYERS {
        let (gate_up, down) = tensor_names(layer);
        for (role, tensor) in [
            (format!("experts_gate_up.{layer}"), gate_up),
            (format!("experts_down.{layer}"), down),
        ] {
            let index = shard_of(&probe, &tensor);
            src = src.role(role, index, tensor).unwrap();
        }
    }
    src
}

fn mlp() -> OpParams {
    OpParams::ExpertMlp {
        hidden: HIDDEN,
        intermediate: INTERMEDIATE,
        experts: EXPERTS,
        top_k: TOP_K,
        // The artifact declares `gelu_pytorch_tanh`.
        activation: ExpertActivation::GeGlu,
    }
}

fn combine() -> OpParams {
    OpParams::Combine {
        hidden: HIDDEN,
        top_k: TOP_K,
        order: CombineOrder::AscendingExpertId,
        output_scale: 1.0,
    }
}

/// Deterministic BF16 activations. Synthetic, and that is the whole caveat.
fn activations(rows: u64, seed: u64) -> Vec<u8> {
    let mut state = seed | 1;
    let mut out = Vec::with_capacity((rows * HIDDEN * 2) as usize);
    for _ in 0..(rows * HIDDEN) {
        state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        let unit = ((state >> 40) as f32) / ((1u32 << 24) as f32) - 0.5;
        out.extend_from_slice(&moxie_kernels::cpu_expert::to_bf16_bits(unit).to_le_bytes());
    }
    out
}

/// A decode-shaped route: two rows of top-k 8, distinct per layer.
///
/// Written by this test. The overlap between the two rows is what makes the
/// union smaller than `rows * top_k`, which is document 03's point about not
/// multiplying active experts by batch rows.
fn decode_route(layer: u32) -> Vec<u32> {
    let mut out = Vec::with_capacity((2 * TOP_K) as usize);
    let mut state = 0x0023_0000u64 | u64::from(layer);
    let mut taken: Vec<u32> = Vec::new();
    for row in 0..2 {
        let mut row_experts: Vec<u32> = Vec::new();
        while row_experts.len() < TOP_K as usize {
            state = state
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            let candidate = ((state >> 33) % EXPERTS) as u32;
            // Rows share their first three selections, so the union is smaller
            // than sixteen and reuse is real rather than assumed.
            let pick = if row == 1 && row_experts.len() < 3 {
                taken[row_experts.len()]
            } else {
                candidate
            };
            if !row_experts.contains(&pick) {
                row_experts.push(pick);
            }
        }
        if row == 0 {
            taken = row_experts.clone();
        }
        out.extend_from_slice(&row_experts);
    }
    out
}

/// A route whose union is the **whole** expert set: sixteen rows of eight,
/// partitioning 0..128.
fn full_route() -> Vec<u32> {
    (0..EXPERTS as u32).collect()
}

fn union_of(route: &[u32]) -> Vec<u32> {
    let mut out = route.to_vec();
    out.sort_unstable();
    out.dedup();
    out
}

// ---------------------------------------------------------------------------
// One whole working set
// ---------------------------------------------------------------------------

/// How much cache a configuration gives, as a ratio of what one layer demands.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Room {
    /// Enough for a whole layer at once: the branch where a prediction is an
    /// equality.
    Roomy,
    /// A quarter of it: the branch where eviction and backpressure make it a
    /// declared lower bound.
    Tight,
    /// One eighth of a whole layer -- sixteen of 128 experts -- which is what
    /// `whole-set-full` streams 45,675,970,560 B through.
    Eighth,
}

impl Room {
    fn of(self, union_bytes: u64) -> u64 {
        let align = |bytes: u64| bytes.div_ceil(256) * 256;
        match self {
            Room::Roomy => align(union_bytes),
            Room::Tight => align(union_bytes.div_ceil(4).max(EXPERT_TOTAL)),
            Room::Eighth => align(LAYER_EXPERTS / 8),
        }
    }
}

struct Config<'a> {
    case: &'a str,
    rows: u64,
    routes: Vec<Vec<u32>>,
    device: Option<&'a RankContext>,
    device_room: Room,
    host_room: Room,
}

struct StepResult {
    /// Every layer's slot buffer, in layer order.
    slots: Vec<Vec<u8>>,
    trace: StepTrace,
    demanded_bytes: u64,
    evictions: u64,
    drains: u64,
    elapsed: std::time::Duration,
}

/// Run one whole working set: every routed layer, one authority, one ledger.
fn run_whole_set(dir: &Path, config: &Config<'_>) -> StepResult {
    let x = activations(config.rows, 0x0021_2026);
    let catalogue = moxie_kernels::expert_mlp_catalogue();
    let device = config.device;
    let scope = device.map_or(Scope::Host, |ctx| Scope::Device(ctx.uuid()));

    // The caches are sized from the *first* layer's demand, so a configuration
    // named "roomy" means the same thing at every layer of a route whose union
    // varies.
    let first_union = union_of(&config.routes[0]).len() as u64 * EXPERT_TOTAL;
    let device_cache = config.device_room.of(first_union);
    let host_cache = config.host_room.of(first_union);

    let mut snapshots = vec![CapacitySnapshot::new(Scope::Host, 8 << 30, 256 * MIB).unwrap()];
    if let Some(ctx) = device {
        snapshots
            .push(CapacitySnapshot::new(Scope::Device(ctx.uuid()), 8 << 30, 256 * MIB).unwrap());
    }
    let mut ledger = Ledger::new(snapshots).unwrap();
    let mut request = ResidencyRequest::new(config.case, host_cache);
    if let Some(ctx) = device {
        request = request.device(ctx.uuid(), device_cache);
    }
    let mut authority = ResidencyAuthority::open(&mut ledger, &request).unwrap();
    let mut residency = device.map(|ctx| DeviceResidency::create(ctx, &mut authority).unwrap());
    let mut src = source(dir);

    let policy = ExpertPolicy {
        device: if device.is_some() {
            StrategyControl::Required
        } else {
            StrategyControl::Off
        },
        host: if device.is_some() {
            StrategyControl::Off
        } else {
            StrategyControl::Auto
        },
        host_placement: StrategyControl::Off,
        // The declared 1 MiB/row threshold sends every expert of this artifact
        // to the CPU -- task 0021 measured exactly that and asserts it -- so a
        // device case has to raise it, and says so rather than hiding it.
        max_transfer_bytes_per_row: EXPERT_TOTAL,
        ..ExpertPolicy::default()
    };

    let started = Instant::now();
    let mut layers: Vec<LayerTrace> = Vec::new();
    let mut slots: Vec<Vec<u8>> = Vec::new();
    let mut demanded = 0u64;
    for (layer, route) in config.routes.iter().enumerate() {
        let layer = layer as u32;
        let union = union_of(route);
        demanded += union.len() as u64 * EXPERT_TOTAL;
        let resident = resident_chunks(&authority, device.map(|_| scope), layer);
        let budget = ExpertBudget {
            device: device.map_or_else(
                || {
                    moxie_types::DeviceUuid::parse("GPU-00000000-0000-0000-0000-000000000000")
                        .unwrap()
                },
                RankContext::uuid,
            ),
            device_pci_bus_id: device
                .map_or_else(String::new, |c| c.capability().pci_bus_id.clone()),
            device_cache_cap_bytes: if device.is_some() { device_cache } else { 0 },
            device_cache_leased_bytes: 0,
            device_arena_free_bytes: if device.is_some() { 64 * MIB } else { 0 },
            host_workspace_bytes: 16 * MIB,
            host_buffer_bytes: 16 * MIB,
            host_cache_cap_bytes: host_cache,
            host_cache_leased_bytes: 0,
            resident,
        };
        let plan = compile_experts(
            &mlp(),
            &combine(),
            route,
            &budget,
            &policy,
            None,
            device.map(|ctx| ExpertKernels {
                capability: ctx.capability(),
                catalogue: &catalogue,
            }),
        )
        .unwrap();
        assert_eq!(plan.groups().len(), union.len(), "layer {layer}");

        let snapshot = LayerSnapshot::take(layer, &authority);
        let mut run = GroupedRun::admit(&mut ledger, plan, roles(layer), None).unwrap();
        if let (Some(ctx), Some(residency)) = (device, residency.as_mut()) {
            run.attach_device(&mut ledger, ctx, residency).unwrap();
        }
        run.load_activations(&x).unwrap();
        run.run_to_completion(
            &mut authority,
            &mut src,
            TurnId::new(u64::from(layer) + 1),
            0,
            u64::MAX,
        )
        .unwrap();
        layers.push(snapshot.close(&run, &authority, &ledger));
        slots.push(run.buffers().slots().to_vec());
        run.close(&mut ledger).unwrap();
        authority.end_turn(TurnId::new(u64::from(layer) + 1));
    }
    let elapsed = started.elapsed();
    let stats = authority.stats();
    let drains: u64 = layers.iter().map(|l| l.cost.backpressure_drains).sum();

    authority.retire_all(Scope::Host);
    if device.is_some() {
        authority.retire_all(scope);
    }
    if let (Some(residency), Some(_)) = (residency, device) {
        residency.close(&mut authority).unwrap();
    }
    authority.close(&mut ledger).unwrap();
    let trace = StepTrace::new(
        artifact_id().as_str(),
        config.case,
        layers,
        &authority,
        &ledger,
    );
    assert!(ledger.outstanding().is_empty());

    StepResult {
        slots,
        trace,
        demanded_bytes: demanded,
        evictions: stats.evictions,
        drains,
        elapsed,
    }
}

/// Where this layer's expert chunks are, read from the authority per chunk.
fn resident_chunks(
    authority: &ResidencyAuthority,
    device_scope: Option<Scope>,
    layer: u32,
) -> ResidentChunks {
    let roles = [
        format!("experts_gate_up.{layer}"),
        format!("experts_down.{layer}"),
    ];
    let mut out = ResidentChunks::none();
    let mut seen: Vec<(u32, u64)> = Vec::new();
    for chunk in authority.outstanding() {
        if !chunk.state.is_ready() {
            continue;
        }
        let Some(expert) = chunk.chunk.slot().expert_index() else {
            continue;
        };
        if !roles.iter().any(|r| r == chunk.chunk.slot().role()) {
            continue;
        }
        let on_device = Some(chunk.scope) == device_scope;
        let in_host = chunk.scope == Scope::Host;
        let key = (expert, chunk.bytes);
        if let Some(index) = seen.iter().position(|k| *k == key) {
            let entry = &mut out.chunks_mut()[index];
            entry.on_device |= on_device;
            entry.in_host |= in_host;
        } else {
            seen.push(key);
            out.push(ChunkResidency {
                expert,
                bytes: chunk.bytes,
                on_device,
                in_host,
            });
        }
    }
    out
}

fn artifact_dir() -> Option<PathBuf> {
    let dir = PathBuf::from(ARTIFACT);
    dir.is_dir().then_some(dir)
}

// ---------------------------------------------------------------------------
// whole-set-decode: every layer, against the reference, in both cache
// configurations
// ---------------------------------------------------------------------------

#[test]
fn the_whole_working_set_runs_on_every_gpu_and_matches_the_cpu_candidate() {
    let _serial = one_at_a_time();
    let Some(dir) = artifact_dir() else {
        println!(
            "SKIPPED: {ARTIFACT} is not present on this machine; the trace itself is swept \
                  over synthetic fixtures in working_set_trace.rs"
        );
        return;
    };
    let count = moxie_cuda::device_count().unwrap();
    assert!(count > 0, "the device lane requires real hardware");

    let routes: Vec<Vec<u32>> = (0..LAYERS).map(decode_route).collect();
    let unions: Vec<usize> = routes.iter().map(|r| union_of(r).len()).collect();
    let demanded: u64 = unions.iter().map(|u| *u as u64 * EXPERT_TOTAL).sum();
    println!(
        "whole-set-decode: {LAYERS} routed layer(s), 2 row(s) of top-k {TOP_K}, unions {:?}, \
         {demanded} B demanded",
        unions
    );

    // The reference, computed **once**: the CPU candidate is bit-identical to
    // task 0019's oracle (proven separately), and its answer does not depend on
    // which card the device candidate ran on.
    let reference = run_whole_set(
        &dir,
        &Config {
            case: "whole-set-decode/reference",
            rows: 2,
            routes: routes.clone(),
            device: None,
            device_room: Room::Roomy,
            host_room: Room::Roomy,
        },
    );
    reference
        .trace
        .reconcile()
        .expect("the host reference's own trace reconciles");
    println!(
        "  cpu candidate: {} layer(s) in {:.2?} (debug build, one run, NOT a benchmark)",
        reference.slots.len(),
        reference.elapsed
    );

    let mut checked = 0u32;
    for ordinal in 0..count {
        let ctx = RankContext::acquire(RankId(0), ordinal).unwrap();
        for room in [Room::Roomy, Room::Tight] {
            let result = run_whole_set(
                &dir,
                &Config {
                    case: "whole-set-decode",
                    rows: 2,
                    routes: routes.clone(),
                    device: Some(&ctx),
                    device_room: room,
                    host_room: room,
                },
            );
            let report = result
                .trace
                .reconcile()
                .unwrap_or_else(|e| panic!("{} {room:?} did not reconcile: {e}", ctx.uuid()));
            assert_eq!(result.demanded_bytes, demanded);
            assert_eq!(result.slots.len(), LAYERS as usize);
            for (layer, (got, want)) in result.slots.iter().zip(reference.slots.iter()).enumerate()
            {
                assert_eq!(
                    got,
                    want,
                    "layer {layer} on {} disagrees with the CPU candidate over the same bytes",
                    ctx.uuid()
                );
            }
            // Each configuration must actually be the branch it is named for.
            let exact = result
                .trace
                .layers
                .iter()
                .filter(|l| matches!(l.predicted.exactness, Exactness::Exact))
                .count();
            match room {
                Room::Roomy => assert_eq!(
                    exact, LAYERS as usize,
                    "a roomy cache produced a lower bound: the exact branch is untested"
                ),
                _ => assert_eq!(
                    exact, 0,
                    "a tight cache produced an exact prediction: the bound branch is untested"
                ),
            }
            if room == Room::Tight {
                assert!(result.evictions > 0, "a tight cache never evicted");
                assert!(result.drains > 0, "a tight cache never refused the queue");
            }
            checked += report.equalities_checked;
            println!(
                "  {} {room:?}: {} equality check(s) ({} lower bound), {} eviction(s), {} \
                 backpressure drain(s), {:.2?}",
                ctx.uuid(),
                report.equalities_checked,
                report.bounds_checked,
                result.evictions,
                result.drains,
                result.elapsed
            );
        }
    }
    println!(
        "  {checked} equality check(s) across {count} card(s); all {} layer(s) bitwise equal to \
         the CPU candidate on every card",
        LAYERS
    );
    println!(
        "NOT model support: the activations are synthetic and the routes are written by this test. \
         Output quality is O2."
    );
}

// ---------------------------------------------------------------------------
// whole-set-full: the artifact's entire routed payload, out of device memory
// ---------------------------------------------------------------------------

#[test]
fn the_artifacts_whole_expert_payload_streams_through_a_restricted_cache() {
    let _serial = one_at_a_time();
    let Some(dir) = artifact_dir() else {
        println!("SKIPPED: {ARTIFACT} is not present on this machine");
        return;
    };
    let count = moxie_cuda::device_count().unwrap();
    assert!(count > 0, "the device lane requires real hardware");

    // Sixteen rows of eight, partitioning the expert set: the union is all 128.
    let route = full_route();
    assert_eq!(union_of(&route).len(), EXPERTS as usize);
    let routes: Vec<Vec<u32>> = (0..LAYERS).map(|_| route.clone()).collect();

    let device_cache = Room::Eighth.of(LAYER_EXPERTS);
    println!(
        "whole-set-full: {WHOLE_SET} B of expert weights over {LAYERS} layer(s) -- 88.5% of the \
         artifact -- through a {device_cache} B device cache holding {} of 128 experts",
        device_cache / EXPERT_TOTAL
    );

    let mut answers: Vec<(String, Vec<Vec<u8>>)> = Vec::new();
    for ordinal in 0..count {
        let ctx = RankContext::acquire(RankId(0), ordinal).unwrap();
        let result = run_whole_set(
            &dir,
            &Config {
                case: "whole-set-full",
                rows: EXPERTS / TOP_K,
                routes: routes.clone(),
                device: Some(&ctx),
                device_room: Room::Eighth,
                host_room: Room::Tight,
            },
        );
        let report = result
            .trace
            .reconcile()
            .unwrap_or_else(|e| panic!("{} did not reconcile: {e}", ctx.uuid()));
        assert_eq!(
            result.demanded_bytes, WHOLE_SET,
            "the whole routed payload was not demanded"
        );
        let admitted: u64 = result
            .trace
            .totals
            .iter()
            .filter(|(scope, _)| matches!(scope, Scope::Device(_)))
            .map(|(_, flow)| flow.admitted_bytes)
            .sum();
        assert!(
            admitted >= WHOLE_SET,
            "the device admitted {admitted} B of a {WHOLE_SET} B working set"
        );
        assert!(
            result.evictions > 0,
            "a cache holding 16 of 128 experts served the whole set without evicting"
        );
        // Backpressure is **not** asserted here, and the reason is worth a line:
        // a queue four deep pins four of the sixteen experts this cache holds, so
        // there is room to admit the fifth and the authority never refuses. That
        // is a property of the queue against the cache, not of the working set,
        // and it is `whole-set-decode/Tight` and task 0022 that exercise a
        // refusal. The count is printed because it is a fact about this run.
        println!(
            "  {}: {admitted} B admitted, {} eviction(s), {} backpressure drain(s), {} equality \
             check(s), {:.2?} (debug build, one run, NOT a benchmark)",
            ctx.uuid(),
            result.evictions,
            result.drains,
            report.equalities_checked,
            result.elapsed
        );
        answers.push((ctx.uuid().to_string(), result.slots));
    }

    // Bitwise equality across the cards, which is also sm_86 against sm_120.
    let (first_name, first) = &answers[0];
    for (name, other) in answers.iter().skip(1) {
        for (layer, (a, b)) in first.iter().zip(other.iter()).enumerate() {
            assert_eq!(a, b, "layer {layer}: {first_name} and {name} disagree");
        }
    }
    let components: usize = first.iter().map(|s| s.len() / 2).sum();
    println!(
        "  {components} BF16 slot component(s) equal across {} card(s)",
        answers.len()
    );
    println!(
        "NOT model support: the activations are synthetic and the route is written by this test, \
         constructed so that its union is the whole expert set. Output quality is O2."
    );
}
