[package]
name = "moxie-repack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "moxie-repack"
path = "src/main.rs"

[dependencies]
moxie-types.workspace = true
moxie-format.workspace = true
moxie-storage.workspace = true
moxie-memory.workspace = true
moxie-host.workspace = true

[lints]
workspace = true
